Feature read only organization
mumuki/mumuki-laboratory pull request #1637
Opened 2021-07-02 21:38 UTC by fedescarpa

## :dart: Goal
Read only mode

## :memo: Details
* Changes in Application Controller to add minimum role for evry controller (default is student)
* Change minimum role to ex student into profile, FAQs, Book, Chapters, Lessons and Exercises controller and validate user permissions depending of user access mode
* Hiding some view elements if needed

## :warning: Dependencies
* https://github.com/mumuki/mumuki-domain/pull/225

## :back: Backwards compatibility
Should be 100%

2021-08-03 23:12 UTC, flbulgarelli requested changes

2021-08-03 23:12 UTC, flbulgarelli commented on spec/features/menu_bar_spec.rb
> +    scenario 'visitor should only see sing out' do
Could we add some more feature tests for the several scenarios of access modes and organization's statuses, please?

2021-08-15 21:25 UTC, fedescarpa commented on app/controllers/application_controller.rb
> -  before_action :validate_active_organization!
I didn't delete this action, it's duplicated, that's why I remove one of both... See line 22 of this file

2021-08-19 15:59 UTC, julian-berbel commented on app/helpers/menu_bar_helper.rb
> +    ].compact
is this needed? :thinking:

2021-08-19 16:04 UTC, julian-berbel commented on app/views/book/show.html.erb
> +    <%   end %>
just being nitpicky but all the double/triple spaces in this file are triggering me

2021-08-19 16:05 UTC, julian-berbel approved these changes
LGTM

2021-08-19 18:23 UTC, flbulgarelli approved these changes
Looks lovely to me :heart:

2021-08-19 20:46 UTC, merged